### ISSUE TITLE
Construire un formulaire de paiement personnalisé

### ISSUE THREAD

**Issue by saidinizar** [zf-fr/zfr-stripe#25]
Bonjour,
Est il possible de construire un formulaire de paiement sans passé par email ?
Merci

**Comment by bakura10** [comment]
Bonjour,

ZfrStripe est une bibliothèque PHP. Pour créer un formulaire PHP vous devez utiliser Stripe.js : https://stripe.com/docs/tutorials/forms

Bonne journée ;)
